<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>XML Sitemap</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style type="text/css">
          :root {
            --background: #0f0c29;
            --foreground: #e1e1e6;
            --primary: #00d6b4; /* Teal from theme */
            --card: #1a1b26;
            --card-border: #2e2e3e;
            --muted: #27273a;
            --muted-foreground: #a1a1aa;
          }
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
            color: var(--foreground);
            background: linear-gradient(270deg, #0f0c29, #302b63, #24243e);
            background-size: 600% 600%;
            animation: Gradient 25s ease infinite;
            margin: 0;
            padding: 4rem 2rem;
            min-height: 100vh;
          }
          @keyframes Gradient {
            0% { background-position: 0% 50%; }
            50% { background-position: 100% 50%; }
            100% { background-position: 0% 50%; }
          }
          .container {
            max-width: 75rem;
            margin: 0 auto;
          }
          h1 {
            font-size: 3rem;
            margin-bottom: 0.5rem;
            font-weight: 700;
            background: linear-gradient(to right, #fff, #a5a5a5);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
          }
          p {
            font-size: 1.1rem;
            color: var(--muted-foreground);
            margin-bottom: 3rem;
          }
          a {
            color: var(--primary);
            text-decoration: none;
            transition: color 0.2s;
          }
          a:hover {
            color: #fff;
            text-decoration: underline;
          }
          .card {
            background-color: rgba(26, 27, 38, 0.8);
            backdrop-filter: blur(10px);
            border: 1px solid var(--card-border);
            border-radius: 1rem;
            overflow: hidden;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
          }
          table {
            width: 100%;
            border-collapse: collapse;
          }
          th {
            background-color: rgba(39, 39, 58, 0.5);
            text-align: left;
            padding: 1.25rem;
            font-weight: 600;
            color: #fff;
            border-bottom: 1px solid var(--card-border);
            text-transform: uppercase;
            font-size: 0.85rem;
            letter-spacing: 0.05em;
          }
          td {
            padding: 1.25rem;
            border-bottom: 1px solid var(--card-border);
            color: var(--muted-foreground);
          }
          tr:last-child td {
            border-bottom: none;
          }
          tr:hover td {
            background-color: rgba(255, 255, 255, 0.03);
            color: var(--foreground);
          }
          .url-col {
            width: 55%;
            color: var(--foreground);
          }
          .badge {
            display: inline-block;
            padding: 0.25rem 0.5rem;
            border-radius: 9999px;
            font-size: 0.75rem;
            font-weight: 500;
            background-color: rgba(0, 214, 180, 0.1);
            color: var(--primary);
            border: 1px solid rgba(0, 214, 180, 0.2);
          }
        </style>
      </head>
      <body>
        <div class="container">
          <h1>XML Sitemap</h1>
          <p>
            Generated by Byte to Offer. This is an XML Sitemap, meant for consumption by search engines.
          </p>
          <div class="card">
            <table>
              <thead>
                <tr>
                  <th class="url-col">URL</th>
                  <th>Last Modified</th>
                  <th>Change Frequency</th>
                  <th>Priority</th>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="sitemap:urlset/sitemap:url">
                  <tr>
                    <td class="url-col">
                      <xsl:variable name="itemURL">
                        <xsl:value-of select="sitemap:loc"/>
                      </xsl:variable>
                      <a href="{$itemURL}">
                        <xsl:value-of select="sitemap:loc"/>
                      </a>
                    </td>
                    <td>
                      <xsl:value-of select="sitemap:lastmod"/>
                    </td>
                    <td>
                      <span class="badge">
                        <xsl:value-of select="sitemap:changefreq"/>
                      </span>
                    </td>
                    <td>
                      <xsl:value-of select="sitemap:priority"/>
                    </td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </div>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
