
import fs from "fs";
import path from "path";
import { loadEnv, calculateChecksum, ensureBackupDir } from "./utils";
import { collection, getDocs, DocumentData } from "firebase/firestore";

// Load env vars BEFORE importing firebase
loadEnv();

// Dynamic import to ensure env vars are present
async function main() {
  console.log("🔒 Vault: Starting Backup Process...");

  // Import firebase after env is loaded
  const { db } = await import("@/lib/firebase");

  // Collections to backup
  // LIMITATION: Client SDK can only read public collections or those allowed by rules.
  // 'users' and 'contact-messages' are private/write-only.
  const COLLECTIONS = ["companies", "problems"];

  const backupData: Record<string, any[]> = {};
  const counts: Record<string, number> = {};

  try {
    for (const colName of COLLECTIONS) {
      console.log(`📦 Fetching collection: ${colName}...`);
      const colRef = collection(db, colName);
      const snapshot = await getDocs(colRef);

      const docs = snapshot.docs.map(doc => ({
        id: doc.id,
        ...doc.data()
      }));

      backupData[colName] = docs;
      counts[colName] = docs.length;
      console.log(`   ✅ Found ${docs.length} documents.`);
    }

    // Prepare Metadata
    const timestamp = new Date().toISOString();
    const dataChecksum = calculateChecksum(backupData);

    const finalBackup = {
      metadata: {
        version: "1.0.0",
        timestamp,
        counts,
        checksum: dataChecksum,
        note: "Generated by Vault Backup Script"
      },
      data: backupData
    };

    // Serialize
    const jsonString = JSON.stringify(finalBackup, null, 2);
    const fullChecksum = calculateChecksum(jsonString);

    // Save
    const backupDir = ensureBackupDir();
    const filename = `backup-${timestamp.replace(/[:.]/g, "-")}.json`;
    const filePath = path.join(backupDir, filename);

    fs.writeFileSync(filePath, jsonString);
    console.log(`💾 Backup saved to: ${filePath}`);

    // VERIFICATION STEP
    console.log("🔍 Verifying backup integrity...");
    const readBack = fs.readFileSync(filePath, "utf-8");
    const readChecksum = calculateChecksum(readBack);

    if (readChecksum !== fullChecksum) {
      throw new Error("❌ Integrity Check Failed! File checksum does not match computed checksum.");
    }

    // Verify internal data checksum
    const parsed = JSON.parse(readBack);
    const internalChecksum = calculateChecksum(parsed.data);
    if (internalChecksum !== parsed.metadata.checksum) {
        throw new Error("❌ Data Integrity Check Failed! Data checksum does not match metadata.");
    }

    console.log("✅ Verification Successful. Backup is safe.");

  } catch (error) {
    console.error("❌ Backup Failed:", error);
    process.exit(1);
  }
}

main();
