import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// ESM dirname equivalent
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const CWD = process.cwd();
const ENV_LOCAL = path.join(CWD, '.env.local');

// Colors for console output
const colors = {
  reset: '\x1b[0m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  red: '\x1b[31m',
  cyan: '\x1b[36m',
  bold: '\x1b[1m'
};

const log = {
  info: (msg) => console.log(`${colors.cyan}ℹ ${msg}${colors.reset}`),
  success: (msg) => console.log(`${colors.green}✔ ${msg}${colors.reset}`),
  warn: (msg) => console.log(`${colors.yellow}⚠ ${msg}${colors.reset}`),
  error: (msg) => console.log(`${colors.red}✖ ${msg}${colors.reset}`),
  header: (msg) => console.log(`\n${colors.bold}${msg}${colors.reset}\n`)
};

console.log(`${colors.bold}✈️  Pilot: Generating CI environment variables...${colors.reset}`);

// Check if .env.local already exists (e.g. in local dev or if cached)
if (fs.existsSync(ENV_LOCAL)) {
    log.warn('.env.local already exists. Skipping generation to avoid overwriting.');
    process.exit(0);
}

// Dummy values sufficient to pass zod validation in src/env.ts
// These are NOT real secrets.
const ciEnvContent = `
# Generated by scripts/generate-ci-env.mjs for CI Build
NEXT_PUBLIC_APP_URL=https://bytetooffer.com
LOG_LEVEL=INFO

# Dummy Firebase Config (Required by src/env.ts for build)
NEXT_PUBLIC_FIREBASE_API_KEY=dummy_ci_key
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=dummy-project.firebaseapp.com
NEXT_PUBLIC_FIREBASE_PROJECT_ID=dummy-project
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=dummy-project.appspot.com
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=123456789
NEXT_PUBLIC_FIREBASE_APP_ID=1:123456789:web:abcdef123456

# Optional but good to have defaults
NEXT_PUBLIC_GOOGLE_ADSENSE_CLIENT_ID=ca-pub-dummy
NEXT_PUBLIC_GOOGLE_ADSENSE_SLOT_ID=dummy_slot
`;

try {
    fs.writeFileSync(ENV_LOCAL, ciEnvContent.trim());
    log.success('Generated .env.local with dummy values for CI.');
} catch (error) {
    log.error(`Failed to generate .env.local: ${error.message}`);
    process.exit(1);
}
