name: Run Unit Tests

on:
  pull_request:
    branches:
      - main  # or 'master' or your main development branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use your project's Node version

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
